Dev
DopamineInjector/dope-node pull request #6
Opened 2024-11-30 14:46 UTC by lukrzak

2024-12-01 16:43 UTC, tpalinski requested changes

2024-12-01 16:43 UTC, tpalinski commented on communication/smartContractHandler.go
> +		utils.VerifySignature(input.Signature, fmt.Sprintf("%v", input.Payload), input.Signature)
sprintf potrafi spaść z rowerka przy tym jsonie. lepiej zrobić json marshall + string z []byte

2024-12-01 16:43 UTC, tpalinski commented on communication/smartContractHandler.go
> +			log.Infof("VM output: %s", out)
masz cały package vm który to robi

2024-12-01 16:43 UTC, tpalinski commented on communication/transactionsHandler.go
> +	blockchain.DopeTransactions.SaveTransaction(&transToSend)
check na to czy masz tyle na koncie?

2024-12-01 16:43 UTC, tpalinski commented on utils/crypto.go
> +	block, _ := pem.Decode([]byte(public))
nie zadziała, samo base64 na bajty powinno być

2024-12-01 16:43 UTC, tpalinski commented on utils/crypto.go
> +func VerifySignature(public string, message string, signature string) (bool, error) {
signature powinien byc []byte

2024-12-02 08:21 UTC, lukrzak commented on communication/transactionsHandler.go
> +	blockchain.DopeTransactions.SaveTransaction(&transToSend)
Jest sprawdzane podczas wysobycia bloku

2024-12-03 08:57 UTC, tpalinski commented
How does the app not respect the config? Please get rid of all the flag stuff in main, otherwise it will be undeployable

2024-12-03 09:07 UTC, tpalinski requested changes
Please use config.toml

2024-12-03 09:07 UTC, tpalinski commented on communication/smartContractHandler.go
> +			out, err := vm.RunContract(&vm.RunContractOpts{BinaryPath: "/bin/dopechain-vm", Entrypoint: input.Payload.Entrypoint, Args: input.Payload.Args, Sender: string(input.Payload.Sender), TransactionId:
get rid of this hardcoded binary, we have everything set up in config.toml

2024-12-03 09:07 UTC, tpalinski commented on communication/smartContractHandler.go
> +		utils.VerifySignature(sndr, string(marshalledPayload), sig)
Why do we need those as strings actually?

2024-12-03 09:07 UTC, tpalinski commented on communication/smartContractHandler.go
> +		json.NewEncoder(w).Encode(output)
We are not setting output property? So always returning empty output?

2024-12-03 09:07 UTC, tpalinski commented on communication/communication.go
> +		http.HandleFunc(SMARTCONTRACT_ENDPOINT, handleSmartContract)
You can also define endpoints like `POST /api/account` and it will handle only this method

2024-12-05 08:08 UTC, merged